import re
import json

SOURCE_FILE = "plot.html"
OUTPUT_FILE = "apworld1.html"  # Outputs clean HTML for your graph page

# Load raw Plotly HTML generated by your private repo
with open(SOURCE_FILE, "r", encoding="utf-8") as f:
    raw_content = f.read()

# 1. Extract Plotly JSON parameters
pattern = r'Plotly\.newPlot\(\s*"[^"]+",\s*(\[.*?\]),\s*(\{.*?\}),\s*(\{.*?\})\s*\)'
match = re.search(pattern, raw_content, re.DOTALL)

if not match:
    raise ValueError("Could not extract Plotly.newPlot configuration from HTML!")

data_json = json.loads(match.group(1))
layout_json = json.loads(match.group(2))
config_json = json.loads(match.group(3))

# 2. Inject Retro Dark Palette into Plotly internal layout settings
DARK_BG = "#12141c"
GRID_COLOR = "rgba(64, 224, 208, 0.15)"
TEXT_COLOR = "#e0fbf8"
TURQUOISE = "#40e0d0"

layout_json["paper_bgcolor"] = DARK_BG
layout_json["plot_bgcolor"] = DARK_BG

if "font" not in layout_json:
    layout_json["font"] = {}
layout_json["font"]["color"] = TEXT_COLOR

for ann in layout_json.get("annotations", []):
    if "font" not in ann:
        ann["font"] = {}
    ann["font"]["color"] = TEXT_COLOR

for axis_key in ["xaxis", "yaxis", "xaxis2", "yaxis2"]:
    if axis_key in layout_json:
        axis = layout_json[axis_key]
        axis["gridcolor"] = GRID_COLOR
        axis["linecolor"] = TURQUOISE
        axis["zerolinecolor"] = GRID_COLOR
        if "title" in axis and isinstance(axis["title"], dict):
            axis["title"]["font"] = {"color": TEXT_COLOR}

if "legend" in layout_json:
    layout_json["legend"]["bgcolor"] = "rgba(18, 20, 28, 0.85)"
    layout_json["legend"]["bordercolor"] = "#1f6e66"
    layout_json["legend"]["font"] = {"color": TEXT_COLOR}

# 3. Assemble target HTML referencing style.css
formatted_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AP Multiworld 1 Progression</title>
    
    <!-- Prevent caching -->
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Expires" content="0" />

    <!-- Google Font for Retro Arcade aesthetic -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">

    <!-- External Retro Arcade Stylesheet -->
    <link rel="stylesheet" href="style.css">

    <!-- Plotly Library -->
    <script charset="utf-8" src="https://cdn.plot.ly/plotly-3.7.0.min.js" integrity="sha256-jvTGqxNp8AGWEcvNLVuKr+8j5dGe9Yw51LQkmDH+IYA=" crossorigin="anonymous"></script>
</head>
<body>

    <header class="page-header">
        <a href="index.html" class="back-button">&larr; BACK TO DASHBOARD</a>
        <h1 class="page-title">AP Multiworld 1 Progression</h1>
    </header>

    <main class="graph-wrapper">
        <div id="plotly-multiworld-chart" class="plotly-graph-div" style="height:100%; width:100%;"></div>
    </main>

    <script>
        window.PlotlyConfig = {{ MathJaxConfig: 'local' }};
        window.PLOTLYENV = window.PLOTLYENV || {{}};

        const chartData = {json.dumps(data_json)};
        const chartLayout = {json.dumps(layout_json)};
        const chartConfig = {json.dumps(config_json)};

        if (document.getElementById("plotly-multiworld-chart")) {{
            Plotly.newPlot("plotly-multiworld-chart", chartData, chartLayout, chartConfig);
        }}
    </script>
</body>
</html>
"""

with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    f.write(formatted_html)

print(f"Successfully styled {SOURCE_FILE} into {OUTPUT_FILE} using external style.css!")
